[memory_usage]
disabled = false
threshold = -1
symbol = " "
style = "bold dimmed green"

[time]
disabled = false
format = '🕙[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "-5"
time_range = "10:00:00-14:00:00"
