# A continuation prompt that displays two filled in arrows
continuation_prompt = '▶▶ '

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

[cmake]
disabled = true

[hostname]
disabled = true

[lua]
disabled = true

[python]
python_binary = "python3"
detect_extensions = []


[username]
disabled = true

[custom.p4client]
description = "Displays perforce client"
command = """
echo "$P4CLIENT"
"""
style = 'red'
shell = ["zsh"]
when = """
if [[ -n "$P4CLIENT" ]]; then
  exit 0
fi
exit 1
"""
format = "p4 client: [$output](green) "

