# Index:
#   Background: Build     # Disable slow background indexing of these files.
#
# InlayHints:
#   BlockEnd: No
#   Designators: Yes
#   Enabled: Yes
#   ParameterNames: Yes
#   DeducedTypes: Yes
#   TypeNameLimit: 24
